[PHP]
engine = On
short_open_tag = Off
precision = 14
output_buffering = 4096
serialize_precision = -1
expose_php = Off
max_execution_time = 120
max_input_time = 120
memory_limit = 256M
error_reporting = E_ALL
display_errors = Off
display_startup_errors = Off
log_errors = On
default_charset = "UTF-8"
file_uploads = On
upload_max_filesize = 32M
post_max_size = 32M
max_file_uploads = 5
extension_dir = "ext"
extension = curl
extension = fileinfo
extension = gd
extension = mbstring
extension = openssl
extension = zip

[Date]
date.timezone = "Europe/Berlin"

[Session]
session.use_strict_mode = 1
session.use_only_cookies = 1
session.cookie_httponly = 1
session.cookie_samesite = "Lax"
session.gc_maxlifetime = 86400
